### PR TITLE
Refactor map demo 

### PR DESCRIPTION
**Pull request by BestOwl**
Refactor map demo to the new OBEX stack

### CODE REVIEW

**Comment by BestOwl** [comment]
`GetFolderListing`, `GetMessageListing`, and `GetMessage` is working now (tested on Android phone).

However, the `GetMessage` call inside `MNS_Listener_ConnectionReceived` will not receive any response.
https://github.com/BestOwl/MyPhone/blob/dd28a43e3b7972a5088130628bb35dd7204b13f5/MyPhone.Demo/MapClient.cs#L528-L538

I checked the device log of my Android phone, it shows that the phone already send a response back. Not sure what went wrong.

@xtremehpx can you help me to check that out?

**Comment by BestOwl** [comment]
@xtremehpx I invited you to become a collaborator of this repo. It would be great if you can push subsequent changes directly to this repo.

**Comment by xtremehpx** [comment]
> `GetFolderListing`, `GetMessageListing`, and `GetMessage` is working now (tested on Android phone).
> 
> However, the `GetMessage` call inside `MNS_Listener_ConnectionReceived` will not receive any response.
> https://github.com/BestOwl/MyPhone/blob/dd28a43e3b7972a5088130628bb35dd7204b13f5/MyPhone.Demo/MapClient.cs#L528-L538
> 
> I checked the device log of my Android phone, it shows that the phone already send a response back. Not sure what went wrong.
> 
> @xtremehpx can you help me to check that out?

I'm actually having similar issue. But in my case the requested message packet is returned from Phone but not back to the calling function. I will pull your branch and see what I can find.

**Comment by xtremehpx** [comment]
I fixed this. But I cannot push the code and create PR?

**Comment by BestOwl** [comment]
What do you mean by saying you cannnot push the code and create PR? If you accept the invitation, you can directly push to this repo.

**Comment by xtremehpx** [comment]
never mind, I created a new PR. Please check.

**Comment by xtremehpx** [comment]
> What do you mean by saying you cannnot push the code and create PR? If you accept the invitation, you can directly push to this repo.

somehow I don't see the invitation anymore, can you please send again?

**Comment by BestOwl** [comment]
> > What do you mean by saying you cannnot push the code and create PR? If you accept the invitation, you can directly push to this repo.
> 
> somehow I don't see the invitation anymore, can you please send again?

https://github.com/BestOwl/MyPhone/invitations

**Comment by xtremehpx** [comment]
Thanks. Accepted the invitation. I updated PR to merge into the "xtremehpx/refactor-map-demo" branch. Please review the changes.

**Comment by BestOwl** [comment]
The notification problem has been resolved!

**Comment by xtremehpx** [comment]
> The notification problem has been resolved!

This is great. I will pull and check it out. BTW, a quick glance at the code, I only see the RequestQueue been used to queue the handle, but never been consumed? is the code complete?

**Pull request merged**
